### ISSUE TITLE
No python 3?

### ISSUE THREAD

**Issue by giovannicimolin** [IBM/ibm-cos-sdk-python#1]
I'm trying to use your sdk on python 3 and I'm getting this error:

```
Python 3.6.2 (default, Aug 24 2017, 10:19:11) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/giovanni/.pyenv/versions/3.6.2/lib/python3.6/site-packages/boto3/__init__.py", line 16, in <module>
    from boto3.session import Session
  File "/home/giovanni/.pyenv/versions/3.6.2/lib/python3.6/site-packages/boto3/session.py", line 27, in <module>
    import botocore.session
  File "/home/giovanni/.pyenv/versions/3.6.2/lib/python3.6/site-packages/botocore/session.py", line 37, in <module>
    import botocore.credentials
  File "/home/giovanni/.pyenv/versions/3.6.2/lib/python3.6/site-packages/botocore/credentials.py", line 27, in <module>
    import httplib
ModuleNotFoundError: No module named 'httplib'

```

**Comment by stevemart** [comment]
What are the versions of boto3 and botocore? Looking at the source code for botocore, I don't see any reference to httplib in many releases https://github.com/boto/botocore/blob/master/botocore/credentials.py

Can you run a `pip freeze | grep boto` from your virtualenv?

**Comment by giovannicimolin** [comment]
This is the output:
`boto3==1.4.7
botocore==1.7.6
`

**Comment by stevemart** [comment]
That's weird... there's no httplib reference in credentials.py in that version either: https://github.com/boto/botocore/blob/1.7.6/botocore/credentials.py#L27

I tried things with a new virtualenv (that used python 3.5 instead of 3.6 (in the bug report) from scratch and it seems OK to me.

```shell
smartinelli-mac ~ $ virtualenv --python=python3.5 boto-test
Running virtualenv with interpreter /usr/local/bin/python3.5
Using base prefix '/Library/Frameworks/Python.framework/Versions/3.5'
New python executable in /Users/stevemar/boto-test/bin/python3.5
Also creating executable in /Users/stevemar/boto-test/bin/python
Installing setuptools, pip, wheel...done.
smartinelli-mac ~ $ source boto-test/bin/activate
(boto-test) smartinelli-mac ~ $ which python
/Users/stevemar/boto-test/bin/python
(boto-test) smartinelli-mac ~ $ which pip
/Users/stevemar/boto-test/bin/pip
(boto-test) smartinelli-mac ~ $ pip install boto3
Collecting boto3
  Downloading boto3-1.4.7-py2.py3-none-any.whl (128kB)
    100% |████████████████████████████████| 133kB 2.9MB/s 
Collecting botocore<1.8.0,>=1.7.0 (from boto3)
  Downloading botocore-1.7.28-py2.py3-none-any.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 450kB/s 
Collecting jmespath<1.0.0,>=0.7.1 (from boto3)
  Downloading jmespath-0.9.3-py2.py3-none-any.whl
Collecting s3transfer<0.2.0,>=0.1.10 (from boto3)
  Downloading s3transfer-0.1.11-py2.py3-none-any.whl (54kB)
    100% |████████████████████████████████| 61kB 9.6MB/s 
Collecting python-dateutil<3.0.0,>=2.1 (from botocore<1.8.0,>=1.7.0->boto3)
  Using cached python_dateutil-2.6.1-py2.py3-none-any.whl
Collecting docutils>=0.10 (from botocore<1.8.0,>=1.7.0->boto3)
  Downloading docutils-0.14-py3-none-any.whl (543kB)
    100% |████████████████████████████████| 552kB 2.4MB/s 
Collecting six>=1.5 (from python-dateutil<3.0.0,>=2.1->botocore<1.8.0,>=1.7.0->boto3)
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, docutils, jmespath, botocore, s3transfer, boto3
Successfully installed boto3-1.4.7 botocore-1.7.28 docutils-0.14 jmespath-0.9.3 python-dateutil-2.6.1 s3transfer-0.1.11 six-1.11.0
(boto-test) smartinelli-mac ~ $ python
Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import boto3
>>> import botocore.credentials
>>> import httplib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'httplib'
>>> exit()
(boto-test) smartinelli-mac ~ $ pip freeze | grep boto
boto3==1.4.7
botocore==1.7.28
```

The last error is expected since i try to import `httplib` (a python2 lib) directly, but you can see that import of `botocore.credentials` worked just fine, which is the bit that is blows up in the bug report.

**Comment by giovannicimolin** [comment]
I've managed to install it, it was a problem with my enviroment manager. 
Using your steps, I could import boto3 with no problems.

**Comment by giovannicimolin** [comment]
The problem with **ibm-cos-sdk** still persists, but I found the problem to be on **ibm-cos-sdk-python-core**, that has a reference to a library that have been renamed on python3. 
There's even an open issue in that repo (#1).

My fix was to replace line 27 of credentials.py on my local installation directory from:
`import httplib`
To:
`import http.client as httplib`

**Comment by stevemart** [comment]
OOps, sorry about the close and re-open. Yes, you are totally right. I see https://github.com/IBM/ibm-cos-sdk-python-core/issues/1 now.

**Comment by zhuojc** [comment]
This issue is being tracked internally and will be resolved in the next patch release.

**Comment by wbhuberIBM** [comment]
@giovannicimolin @stevemart - Python 3 is now supported since 1.0.2 version.
