### ISSUE TITLE
Failure during the download bucket content using IBM BOTO3 

### ISSUE THREAD

**Issue by srikrbha** [IBM/ibm-cos-sdk-python#12]
This issue is a continuation of issue #8 .
We are trying to download the bucket content using IBM BOTO3 and it fails with below error message:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/ibm/scoring/python/workdir/batch_input_abe514e7e26c7c8c137e80162fdfdfe8/test_/.2f6C9b89'

This is the stacktrace that we get:
```
2018/06/13 20:43:36,334|WARNING|servicer.scoring_grpc_batch_servicer:70|abe514e7e26c7c8c137e80162fdfdfe8|608f18bb-9269-4a0e-a40a-daf60eb057f1:Batch Deploy and Score error stacktrace: Traceback (most recent call last):
  File "/opt/ibm/scoring/python/py_scoring_base/py_runtime/caffe_runtime.py", line 418, in predict_batch
    self._score_caffe_model_batch(details_json, caffe_entry, input, output)
  File "/opt/ibm/scoring/python/py_scoring_base/py_runtime/caffe_runtime.py", line 327, in _score_caffe_model_batch
    BatchConnector.download(in_connector_parms)
  File "/opt/ibm/scoring/python/py_common_base/utils/batch_connector.py", line 97, in download
    return BatchConnector.aws_cos_download(param)
  File "/opt/ibm/scoring/python/py_common_base/utils/batch_connector.py", line 187, in aws_cos_download
    amz.meta.client.download_file(bucket_name, object.key, download_path+'/'+object.key)
  File "/opt/conda/lib/python3.6/site-packages/ibm_boto3/s3/inject.py", line 126, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/opt/conda/lib/python3.6/site-packages/ibm_boto3/s3/transfer.py", line 299, in download_file
    future.result()
  File "/opt/conda/lib/python3.6/site-packages/ibm_s3transfer/futures.py", line 73, in result
    return self._coordinator.result()
  File "/opt/conda/lib/python3.6/site-packages/ibm_s3transfer/futures.py", line 233, in result
    raise self._exception
  File "/opt/conda/lib/python3.6/site-packages/ibm_s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/opt/conda/lib/python3.6/site-packages/ibm_s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/opt/conda/lib/python3.6/site-packages/ibm_s3transfer/download.py", line 568, in _main
    fileobj.seek(offset)
  File "/opt/conda/lib/python3.6/site-packages/ibm_s3transfer/utils.py", line 317, in seek
    self._open_if_needed()
  File "/opt/conda/lib/python3.6/site-packages/ibm_s3transfer/utils.py", line 300, in _open_if_needed
    self._fileobj = self._open_function(self._filename, self._mode)
  File "/opt/conda/lib/python3.6/site-packages/ibm_s3transfer/utils.py", line 226, in open
    return open(filename, mode)
**FileNotFoundError: [Errno 2] No such file or directory: '/opt/ibm/scoring/python/workdir/batch_input_abe514e7e26c7c8c137e80162fdfdfe8/test_/.2f6C9b89'**

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/ibm/scoring/python/py_grpc_base/servicer/scoring_grpc_batch_servicer.py", line 57, in BatchDeployAndScore
    request.output
  File "/opt/ibm/scoring/python/py_scoring_base/py_runtime/caffe_runtime.py", line 467, in predict_batch
    ) from ex
py_common.errors.WmlBatchScoringException: (status_code=500, trace=abe514e7e26c7c8c137e80162fdfdfe8, code=load_model_failure, message=[Errno 2] No such file or directory: '/opt/ibm/scoring/python/workdir/batch_input_abe514e7e26c7c8c137e80162fdfdfe8/test_/.2f6C9b89', more_info=None, target_type=None, target_name=None)
```

This is the code we follow to download the files:

```
amz = ibm_boto3.resource('s3',
                                 endpoint_url=service_endpoint,
                                 aws_access_key_id=aws_access_key_id,
                                 aws_secret_access_key=aws_secret_access_key)
my_bucket = amz.Bucket(bucket_name)
for object in my_bucket.objects.all():
     amz.meta.client.download_file(bucket_name, object.key, download_path+'/'+object.key)
```

Here download_path is:
`/opt/ibm/scoring/python/workdir/batch_input_abe514e7e26c7c8c137e80162fdfdfe8`

I suspect that `test_/` string might get added here from `object.key` in the last line of the code snippet.

**Comment by paul-carron** [comment]
@srikrbha could you show me how you're declaring bucket_name and download_path?

**Comment by srikrbha** [comment]
@paul-carron Sorry for the late reply.
`download_path` is being declared this way:
```download_path = base_download_path + "/batch_input_" + request_id```
Before using the `download_path` though, we are executing the command:
```os.makedirs(download_path)```
`bucket_name` gets declared this way:
```bucket_name = aws_connector_params['bucket_name']```

**Comment by paul-carron** [comment]
Thanks @srikrbha.

I see in issue #8 this happened intermittently. Does it happen consistently with some keys and not happen at all with others? E.g. does it happen every time with the above key but not with other keys? If so, can you confirm that there is no 'test' folder under that keey in the bucket?

**Comment by srikrbha** [comment]
@paul-carron 
Here is a screenshot of the bucket:
<img width="435" alt="screen shot 2018-08-14 at 2 06 45 pm" src="https://user-images.githubusercontent.com/41949442/44081047-526bcfe6-9f9d-11e8-8d41-562494497dc2.png">

This happens intermittently (I am yet to verify if it is for the same key).
Also our code goes like this:
```
download_path = base_download_path + "/batch_input_" + request_id
if os.path.isdir(download_path):
                shutil.rmtree(download_path)
os.makedirs(download_dir_name)

followed by the rest of the code I pasted to download the contents
```

**Comment by paul-carron** [comment]
@srikrbha out of curiosity, what happens if you create the _test folder in your download_path and run your script?

**Comment by srikrbha** [comment]
Thanks.Will try it out. The directory is being generated automatically and the issue is intermittent, also this doesn't seem to have happened for sometime. I will close the issue for now. Will reopen it if this happens once again.
