### ISSUE TITLE
AttributeError: 'Config' object has no attribute 'inject_host_prefix'

### ISSUE THREAD

**Issue by gamcoh** [IBM/ibm-cos-sdk-python#23]
I'm trying to execute this [script](https://github.com/gamcoh/Xml2Json/blob/master/upload2bucket.py) but i get this error :

```
Traceback (most recent call last):
  File "upload2bucket.py", line 39, in <module>
    main()
  File "upload2bucket.py", line 23, in main
    endpoint_url=credentials['url']
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_boto3/__init__.py", line 92, in resource
    return _get_default_session().resource(*args, **kwargs)
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_boto3/session.py", line 476, in resource
    config=config)
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_boto3/session.py", line 324, in client
    token_manager=token_manager, config=config)
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_botocore/session.py", line 900, in create_client
    client_config=config, api_version=api_version)
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_botocore/client.py", line 86, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_botocore/client.py", line 328, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_botocore/args.py", line 47, in get_client_args
    endpoint_url, is_secure, scoped_config)
  File "/Users/gamliel/anaconda3/lib/python3.6/site-packages/ibm_botocore/args.py", line 142, in compute_client_args
    inject_host_prefix=client_config.inject_host_prefix,
AttributeError: 'Config' object has no attribute 'inject_host_prefix'
```

My env:
```
Python 3.6.5 :: Anaconda, Inc.
botocore==1.12.26
ibm-cos-sdk==2.3.2
ibm-cos-sdk-core==2.4.4
ibm-cos-sdk-s3transfer==2.4.4
```

**Comment by gamcoh** [comment]
Apparently the versions need to be:
```
ibm-cos-sdk-core==2.3.2
ibm-cos-sdk-s3transfer==2.3.2
```
