### ISSUE TITLE
Unable to download files from COS when root logger set to DEBUG

### ISSUE THREAD

**Issue by jaymindesai** [IBM/ibm-cos-sdk-python#37]
When root logger is set to level `DEBUG`, I'm unable to download the file from COS. The `download_file` call as mentioned below goes into infinite wait stage..
```python3
cos_connection = ibm_boto3.resource('s3', endpoint_url=cos_endpoint, aws_access_key_id=cos_access_key, aws_secret_access_key=cos_secret_key)
cos_connection.meta.client.download_file(cos_bucket_name, cos_source_path, download_path)
```
The last logs I see before the code enters wait state are
```sh
{'time':'2020-09-23 23:43:46,643', 'name': 'ibm_s3transfer.utils', 'level': 'DEBUG', 'message': 'Acquiring 0'}
{'time':'2020-09-23 23:43:46,644', 'name': 'ibm_s3transfer.utils', 'level': 'DEBUG', 'message': 'Releasing acquire 0/None'}
```
If I terminate the process using a keyboard interrupt, I see the following trace
```python
{'time':'2020-09-23 23:45:47,404', 'name': 'ibm_s3transfer.futures', 'level': 'DEBUG', 'message': 'TransferCoordinator(transfer_id=0) cancel() called'}
Traceback (most recent call last):
  File "/opt/miniconda3/bin/run_some_server", line 8, in <module>
    sys.exit(main())
  File "/opt/miniconda3/lib/python3.7/site-packages/some_packge/service/some_server.py", line 96, in main
    SOMEServer().run()
  File "/opt/miniconda3/lib/python3.7/site-packages/some_packge/service/some_server.py", line 74, in run
    serviceX_pb2_grpc.add_SomeService_to_server(SomeService(self._config),
  File "/opt/miniconda3/lib/python3.7/site-packages/some_packge/service/services/some_servicer.py", line 43, in __init__
    self._X_system = SOMESystem(config)
  File "/opt/miniconda3/lib/python3.7/site-packages/some_packge/business/some_system.py", line 54, in __init__
    self._model, tokenizer = load_model_and_tokenizer_from_config(self._config, self._logger)
  File "/opt/miniconda3/lib/python3.7/site-packages/some_packge/business/model_providers/model_provider_factory.py", line 54, in load_model_and_tokenizer_from_config
    return model_provider.load_model(), model_provider.load_tokenizer()
  File "/opt/miniconda3/lib/python3.7/site-packages/some_packge/business/model_providers/cos_model_provider.py", line 82, in load_model
    filesys_destination_path = self.pull_cos_model(self._cos_model_filename)
  File "/opt/miniconda3/lib/python3.7/site-packages/some_packge/logging_tools/function_loggers.py", line 28, in wrapper
    result = f(*args, **kwargs)
  File "/opt/miniconda3/lib/python3.7/site-packages/some_packge/business/model_providers/cos_model_provider.py", line 73, in pull_cos_model
    self._cos_connection.meta.client.download_file(self._cos_bucket_name, cos_source_path, download_path)
  File "/opt/miniconda3/lib/python3.7/site-packages/ibm_boto3/s3/inject.py", line 172, in download_file
    extra_args=ExtraArgs, callback=Callback)
  File "/opt/miniconda3/lib/python3.7/site-packages/ibm_boto3/s3/transfer.py", line 307, in download_file
    future.result()
  File "/opt/miniconda3/lib/python3.7/site-packages/ibm_s3transfer/futures.py", line 109, in result
    raise e
  File "/opt/miniconda3/lib/python3.7/site-packages/ibm_s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/opt/miniconda3/lib/python3.7/site-packages/ibm_s3transfer/futures.py", line 260, in result
    self._done_event.wait(MAXINT)
  File "/opt/miniconda3/lib/python3.7/threading.py", line 552, in wait
    signaled = self._cond.wait(timeout)
  File "/opt/miniconda3/lib/python3.7/threading.py", line 296, in wait
    waiter.acquire()
KeyboardInterrupt
```
 This is how my current log config looks like
```ini
[loggers]
keys=root

[handlers]
keys=consoleHandler

[formatters]
keys=simpleFormatter,jsonFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=jsonFormatter
args=(sys.stdout,)

[formatter_simpleFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
datefmt=

[formatter_jsonFormatter]
format={'time':'%(asctime)s', 'name': '%(name)s', 'level': '%(levelname)s', 'message': '%(message)s'}
datefmt=
```

If I change the level of `root` logger to `INFO`, things work fine. I'm using `ibm_cos_sdk` version `2.7.0`. I tried some older versions as well `2.6.2` and `2.6.3` but I see the same error. Any idea what I'm doing wrong here?

Thanks!

**Comment by jaymindesai** [comment]
We need `DEBUG` logs and this is how I'm working around the issue for now:
```python3
cos_connection = ibm_boto3.resource('s3', endpoint_url=cos_endpoint, aws_access_key_id=cos_access_key, aws_secret_access_key=cos_secret_key)
logging.getLogger().setLevel(logging.INFO)
cos_connection.meta.client.download_file(cos_bucket_name, cos_source_path, download_path)
logging.getLogger().setLevel(self._logger.level)
```

**Comment by IBMeric** [comment]
Thank you for your message. I created a test script using your two lines of code and version 2.7.0 of the SDK. I am able to use `download_file` with debug logging enabled and cannot reproduce the behavior you observe. The two log messages you cited are the beginning and end of the transfer. There should be execution messages in between. I saw two sets of those in my output, one nested inside the other (see below).

```
2020-09-29 17:27:52,089 [ibm_s3transfer.utils:34162] DEBUG Acquiring 0
2020-09-29 17:27:52,089 [ibm_s3transfer.tasks:34162] DEBUG DownloadSubmissionTask(transfer_id=0, {'transfer_future': <ibm_s3transfer.futures.TransferFuture object at 0x7fde4adc6d50>}) about to wait for the following futures []
2020-09-29 17:27:52,089 [ibm_s3transfer.tasks:34162] DEBUG DownloadSubmissionTask(transfer_id=0, {'transfer_future': <ibm_s3transfer.futures.TransferFuture object at 0x7fde4adc6d50>}) done waiting for dependent futures
2020-09-29 17:27:52,090 [ibm_s3transfer.tasks:34162] DEBUG Executing task DownloadSubmissionTask(transfer_id=0, {'transfer_future': <ibm_s3transfer.futures.TransferFuture object at 0x7fde4adc6d50>}) with kwargs {'client': <ibm_botocore.client.S3 object at 0x7fde4ae1e910>, 'config': <ibm_boto3.s3.transfer.TransferConfig object at 0x7fde4adc6550>, 'osutil': <ibm_s3transfer.utils.OSUtils object at 0x7fde4adc6590>, 'request_executor': <ibm_s3transfer.futures.BoundedExecutor object at 0x7fde4adc6850>, 'transfer_future': <ibm_s3transfer.futures.TransferFuture object at 0x7fde4adc6d50>, 'io_executor': <ibm_s3transfer.futures.BoundedExecutor object at 0x7fde4adc69d0>}
2020-09-29 17:27:52,091 [ibm_botocore.hooks:34162] DEBUG Event before-parameter-build.s3.HeadObject: calling handler <function sse_md5 at 0x7fde4b9d4320>
2020-09-29 17:27:52,091 [ibm_botocore.hooks:34162] DEBUG Event before-parameter-build.s3.HeadObject: calling handler <function validate_bucket_name at 0x7fde4b9d4290>
... (more logs)
2020-09-29 17:27:52,118 [ibm_botocore.hooks:34162] DEBUG Event needs-retry.s3.HeadObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <ibm_botocore.utils.S3RegionRedirector object at 0x7fde4ae1ef50>>
2020-09-29 17:27:52,118 [ibm_s3transfer.futures:34162] DEBUG Submitting task ImmediatelyWriteIOGetObjectTask(transfer_id=0, {'bucket': 'github37_42610', 'key': 'myfile_06194', 'extra_args': {}}) to executor <ibm_s3transfer.futures.BoundedExecutor object at 0x7fde4adc6850> for transfer request: 0.
2020-09-29 17:27:52,119 [ibm_s3transfer.utils:34162] DEBUG Acquiring 0
2020-09-29 17:27:52,119 [ibm_s3transfer.tasks:34162] DEBUG ImmediatelyWriteIOGetObjectTask(transfer_id=0, {'bucket': 'github37_42610', 'key': 'myfile_06194', 'extra_args': {}}) about to wait for the following futures []
2020-09-29 17:27:52,119 [ibm_s3transfer.tasks:34162] DEBUG ImmediatelyWriteIOGetObjectTask(transfer_id=0, {'bucket': 'github37_42610', 'key': 'myfile_06194', 'extra_args': {}}) done waiting for dependent futures
2020-09-29 17:27:52,119 [ibm_s3transfer.tasks:34162] DEBUG Executing task ImmediatelyWriteIOGetObjectTask(transfer_id=0, {'bucket': 'github37_42610', 'key': 'myfile_06194', 'extra_args': {}}) with kwargs {'client': <ibm_botocore.client.S3 object at 0x7fde4ae1e910>, 'bucket': 'github37_42610', 'key': 'myfile_06194', 'fileobj': <ibm_s3transfer.utils.DeferredOpenFile object at 0x7fde4ade1bd0>, 'extra_args': {}, 'callbacks': [], 'max_attempts': 5, 'download_output_manager': <ibm_s3transfer.download.DownloadFilenameOutputManager object at 0x7fde4aec2f10>, 'io_chunksize': 262144, 'bandwidth_limiter': None}
2020-09-29 17:27:52,120 [ibm_botocore.hooks:34162] DEBUG Event before-parameter-build.s3.GetObject: calling handler <function sse_md5 at 0x7fde4b9d4320>
2020-09-29 17:27:52,120 [ibm_botocore.hooks:34162] DEBUG Event before-parameter-build.s3.GetObject: calling handler <function validate_bucket_name at 0x7fde4b9d4290>
2020-09-29 17:27:52,120 [ibm_s3transfer.utils:34162] DEBUG Releasing acquire 0/None
2020-09-29 17:27:52,121 [ibm_botocore.hooks:34162] DEBUG Event before-parameter-build.s3.GetObject: calling handler <bound method S3RegionRedirector.redirect_from_cache of <ibm_botocore.utils.S3RegionRedirector object at 0x7fde4ae1ef50>>
... (more logs)
2020-09-29 17:27:52,136 [ibm_botocore.hooks:34162] DEBUG Event needs-retry.s3.GetObject: calling handler <bound method S3RegionRedirector.redirect_from_error of <ibm_botocore.utils.S3RegionRedirector object at 0x7fde4ae1ef50>>
2020-09-29 17:27:52,136 [ibm_s3transfer.tasks:34162] DEBUG IOWriteTask(transfer_id=0, {'offset': 0}) about to wait for the following futures []
2020-09-29 17:27:52,136 [ibm_s3transfer.tasks:34162] DEBUG IOWriteTask(transfer_id=0, {'offset': 0}) done waiting for dependent futures
2020-09-29 17:27:52,137 [ibm_s3transfer.tasks:34162] DEBUG Executing task IOWriteTask(transfer_id=0, {'offset': 0}) with kwargs {'fileobj': <ibm_s3transfer.utils.DeferredOpenFile object at 0x7fde4ade1bd0>, 'offset': 0}
2020-09-29 17:27:52,137 [ibm_s3transfer.tasks:34162] DEBUG IORenameFileTask(transfer_id=0, {'final_filename': '/tmp/myfile_06194'}) about to wait for the following futures []
2020-09-29 17:27:52,137 [ibm_s3transfer.tasks:34162] DEBUG IORenameFileTask(transfer_id=0, {'final_filename': '/tmp/myfile_06194'}) done waiting for dependent futures
2020-09-29 17:27:52,137 [ibm_s3transfer.tasks:34162] DEBUG Executing task IORenameFileTask(transfer_id=0, {'final_filename': '/tmp/myfile_06194'}) with kwargs {'fileobj': <ibm_s3transfer.utils.DeferredOpenFile object at 0x7fde4ade1bd0>, 'final_filename': '/tmp/myfile_06194', 'osutil': <ibm_s3transfer.utils.OSUtils object at 0x7fde4adc6590>}
2020-09-29 17:27:52,137 [ibm_s3transfer.utils:34162] DEBUG Releasing acquire 0/None
```

For reference, I am using Python 3.7.9 downloaded from python.org using `pyenv` on Linux. I also configured my logging in-code because I am not familiar with using the INI format you presented. Here is the setup code I used:

```
def setup_logging():
    stderr = logging.StreamHandler()
    stderr.setFormatter(logging.Formatter('%(asctime)s [%(name)s:%(process)d] %(levelname)s %(message)s'))
    stderr.setLevel(logging.DEBUG)
    rootlogger = logging.getLogger()
    rootlogger.setLevel(logging.DEBUG)
    rootlogger.addHandler(stderr)
    logger = rootlogger.getChild('mylogger')
    return logger

logger = setup_logging()  # No additional logger configuration before running your code.
```

If you create a simple, standalone application, are you able to reproduce the problem?

**Comment by IBMeric** [comment]
@jaymindesai Could you provide an update if you are still having trouble or close the ticket if the problem has been resolved?

**Comment by jaymindesai** [comment]
@IBMeric Sorry about that! I will try to reproduce this issue and get back to you soon.

**Comment by IBMeric** [comment]
Closing this ticket because of inactivity. If you continue to have a problem, please reopen.
