### ISSUE TITLE
python 3.9 - ModuleNotFoundError: No module named 'xml.etree.cElementTree'

### ISSUE THREAD

**Issue by powellquiring** [IBM/ibm-cos-sdk-python#40]
```
$ python --version
Python 3.9.0a5
$ pip install ibm-cos-sdk
Requirement already satisfied: ibm-cos-sdk in ./venv/lib/python3.9/site-packages (2.8.0)
Requirement already satisfied: ibm-cos-sdk-core==2.8.0 in ./venv/lib/python3.9/site-packages (from ibm-cos-sdk) (2.8.0)
Requirement already satisfied: ibm-cos-sdk-s3transfer==2.8.0 in ./venv/lib/python3.9/site-packages (from ibm-cos-sdk) (2.8.0)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in ./venv/lib/python3.9/site-packages (from ibm-cos-sdk) (0.10.0)
Requirement already satisfied: docutils<0.16,>=0.10 in ./venv/lib/python3.9/site-packages (from ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (0.15.2)
Requirement already satisfied: requests<3.0,>=2.18 in ./venv/lib/python3.9/site-packages (from ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (2.24.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in ./venv/lib/python3.9/site-packages (from ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (2.8.1)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.9/site-packages (from requests<3.0,>=2.18->ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in ./venv/lib/python3.9/site-packages (from requests<3.0,>=2.18->ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./venv/lib/python3.9/site-packages (from requests<3.0,>=2.18->ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.9/site-packages (from requests<3.0,>=2.18->ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (2020.6.20)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.9/site-packages (from python-dateutil<3.0.0,>=2.1->ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (1.15.0)
$ python
Python 3.9.0a5 (default, Oct  7 2020, 19:03:35)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_boto3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pquiring/github.com/powellquiring/bridgepy/tmp/venv/lib/python3.9/site-packages/ibm_boto3/__init__.py", line 16, in <module>
    from ibm_boto3.session import Session
  File "/Users/pquiring/github.com/powellquiring/bridgepy/tmp/venv/lib/python3.9/site-packages/ibm_boto3/session.py", line 27, in <module>
    import ibm_botocore.session
  File "/Users/pquiring/github.com/powellquiring/bridgepy/tmp/venv/lib/python3.9/site-packages/ibm_botocore/session.py", line 28, in <module>
    import ibm_botocore.configloader
  File "/Users/pquiring/github.com/powellquiring/bridgepy/tmp/venv/lib/python3.9/site-packages/ibm_botocore/configloader.py", line 19, in <module>
    from ibm_botocore.compat import six
  File "/Users/pquiring/github.com/powellquiring/bridgepy/tmp/venv/lib/python3.9/site-packages/ibm_botocore/compat.py", line 149, in <module>
    import xml.etree.cElementTree
ModuleNotFoundError: No module named 'xml.etree.cElementTree'
>>>
```

python 3.8.2 all is good:
```
$ python --version
Python 3.8.2
$ pip install ibm-cos-sdk

Requirement already satisfied: ibm-cos-sdk in ./venv/lib/python3.8/site-packages (2.8.0)
Requirement already satisfied: ibm-cos-sdk-core==2.8.0 in ./venv/lib/python3.8/site-packages (from ibm-cos-sdk) (2.8.0)
Requirement already satisfied: ibm-cos-sdk-s3transfer==2.8.0 in ./venv/lib/python3.8/site-packages (from ibm-cos-sdk) (2.8.0)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in ./venv/lib/python3.8/site-packages (from ibm-cos-sdk) (0.10.0)
Requirement already satisfied: docutils<0.16,>=0.10 in ./venv/lib/python3.8/site-packages (from ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (0.15.2)
Requirement already satisfied: requests<3.0,>=2.18 in ./venv/lib/python3.8/site-packages (from ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (2.24.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in ./venv/lib/python3.8/site-packages (from ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (2.8.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in ./venv/lib/python3.8/site-packages (from requests<3.0,>=2.18->ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (1.25.11)
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.8/site-packages (from requests<3.0,>=2.18->ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in ./venv/lib/python3.8/site-packages (from requests<3.0,>=2.18->ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in ./venv/lib/python3.8/site-packages (from requests<3.0,>=2.18->ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (2.10)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.8/site-packages (from python-dateutil<3.0.0,>=2.1->ibm-cos-sdk-core==2.8.0->ibm-cos-sdk) (1.15.0)
$ python
Python 3.8.2 (default, Jun  3 2020, 10:16:52)
[Clang 11.0.0 (clang-1100.0.33.17)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ibm_boto3
```

**Comment by IBMeric** [comment]
Thank you for your finding, but we do not support pre-release versions of Python. The release version of 3.9.0 does not have this problem. Please note that https://github.com/IBM/ibm-cos-sdk-python-core/issues/10 has not been resolved but will be in a future release.

If this solves your problem, please mark the ticket closed.

**Comment by powellquiring** [comment]
You are right!  Thanks.
